server:
  port: 8686
spring:

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health_search?characterEncoding=utf-8
    username: root
    password: 135663
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ZongHikariPool
      maximum-pool-size: 12
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: select 1


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/benben/health/mapper/xml/*.xml
